<?php
/**
 * TactiFC — Indra Sjafri tactic definitions.
 * Expanded by tools/add_tactics.php.
 *
 * Historical tactics are "inspired by" the managers and teams named — gameplay
 * recreations for EA Sports FC, not exact reproductions. DNA is a subjective
 * fan-recreation profile (0-100), not an objective measure.
 */

return [
    [
        'id' => 'sjafri-indonesia-u19-2013',
        'manager' => 'Indra Sjafri',
        'club' => 'Indonesia',
        'season' => '2013',
        'formation' => '4-2-3-1',
        'style' => ['High Press', 'Attacking', 'Disciplined'],
        'difficulty' => 'Intermediate',
        'description' => "Inspired by Sjafri's Indonesia U-19 — the AFF U-19 champions, an energetic young side built on discipline and quick attacking.",
        'philosophy' => "Inspired by Sjafri's Indonesia U-19: press with youthful energy, stay disciplined, and attack quickly through technical wide players.",
        'withBall' => '4-2-3-1',
        'withoutBall' => '4-4-2',
        'gameModes' => ['Career Mode', 'Clubs', 'Kick-Off'],
        'tags' => ['High Press', 'Attacking', 'Disciplined', 'Fast Wingers'],
        'dna' => ['Possession' => 68, 'Pressing' => 82, 'Directness' => 72, 'Defensive Solidity' => 76, 'Width' => 76, 'Tempo' => 84, 'Counter-Attacking' => 78, 'Creativity' => 72],
        'variations' => ['4-3-3', '4-4-2'],
        'buildUp' => 'Fast Build Up',
        'defensiveApproach' => 'High Press',
        'width' => 6,
        'depth' => 7,
        'attackingFocus' => 'Attacking',
        'phases' => [
            'buildUp' => 'Quick and organised. The centre-backs split, the double pivot screens, and the full-backs push on. The ball is moved forward quickly with short, purposeful passes.',
            'progression' => 'The number ten finds space between the lines while the wide players attack the flanks. The ball is moved quickly and diagonally to create space.',
            'finalThird' => 'The striker pins the centre-backs, the number ten creates, and the wide players attack the box. Chances come from quick combinations and crosses.',
            'defensiveTransition' => 'Immediate counter-press led by the front players, winning the ball back high and attacking an unset defence.',
            'defensiveShape' => 'A compact 4-4-2 with the number ten dropping into midfield. The block is disciplined and mid-height, protecting the centre and forcing play wide.',
        ],
        'howToPlay' => [
            'haveBall' => ['Attack quickly through the number ten and wide players.', 'Push the full-backs high for width.', 'Use energetic short passing.', 'Shoot and cross early.'],
            'loseBall' => ['Counter-press immediately.', 'Win the ball back high.', 'Recover into the 4-4-2 if needed.', 'Press in coordinated bursts.'],
            'opponentBall' => ['Keep a compact mid block.', 'Force the ball wide.', 'Stay compact centrally.', 'Rotate the press.'],
            'winning' => ['Reduce pressing intensity.', 'Drop the block deeper.', 'Slow the tempo with possession.'],
            'losing' => ['Press higher and push the line up.', 'Add box runners.', 'Increase tempo and crossing volume.'],
        ],
        'adjustments' => [
            ['situation' => 'Opponent is pressing high', 'options' => ['Use the double pivot as a safe outlet', 'Go long to the striker', 'Trigger the wide players in behind', 'Keep the goalkeeper as an option']],
            ['situation' => 'Opponent is defending very deep', 'options' => ['Push both full-backs high', 'Add late runners into the box', 'Use crosses and cut-backs', 'Increase width']],
            ['situation' => 'You are protecting a lead', 'options' => ['Reduce pressing intensity', 'Drop the block deeper', 'Keep the full-backs home', 'Keep possession to protect the lead']],
        ],
    ],

    [
        'id' => 'sjafri-indonesia-u20-2023',
        'manager' => 'Indra Sjafri',
        'club' => 'Indonesia U-20',
        'season' => '2023',
        'formation' => '4-3-3',
        'style' => ['High Press', 'Counter Attack', 'Disciplined'],
        'difficulty' => 'Intermediate',
        'description' => "Inspired by Sjafri's Indonesia U-20 — a disciplined, hard-working young side built for a high-intensity modern game.",
        'philosophy' => "Inspired by Sjafri's Indonesia U-20: press hard in coordinated blocks, stay compact and organised, and counter with pace.",
        'withBall' => '4-3-3',
        'withoutBall' => '4-4-2',
        'gameModes' => ['Career Mode', 'Clubs', 'Kick-Off'],
        'tags' => ['High Press', 'Counter Attack', 'Disciplined', 'Compact'],
        'dna' => ['Possession' => 62, 'Pressing' => 86, 'Directness' => 74, 'Defensive Solidity' => 84, 'Width' => 72, 'Tempo' => 86, 'Counter-Attacking' => 84, 'Creativity' => 68],
        'variations' => ['4-2-3-1', '4-1-4-1'],
        'buildUp' => 'Fast Build Up',
        'defensiveApproach' => 'High Press',
        'width' => 6,
        'depth' => 8,
        'attackingFocus' => 'Counter Attack',
        'phases' => [
            'buildUp' => 'Direct and safe. The centre-backs look forward early, the pivot screens, and the full-backs push high. The ball is moved quickly to the front players.',
            'progression' => 'High-tempo and vertical. The midfield three links play while the inside forwards attack the half-spaces. The ball is moved forward within a few passes.',
            'finalThird' => 'The striker pins the centre-backs, the inside forwards attack the box at speed, and the midfielders arrive late. Chances come from fast breaks.',
            'defensiveTransition' => 'Coordinated counter-press to win the ball back high, especially in wide areas.',
            'defensiveShape' => 'A high 4-4-2 pressing block with the wide forwards dropping into midfield. The line is high and compact, forcing the opponent into hurried passes.',
        ],
        'howToPlay' => [
            'haveBall' => ['Attack vertically and fast.', 'Use the inside forwards.', 'Push the full-backs high.', 'Use your energy and fitness.'],
            'loseBall' => ['Counter-press immediately.', 'Win the ball back high.', 'Recover into the 4-4-2 if needed.', 'Manage stamina across the front line.'],
            'opponentBall' => ['Keep a high line.', 'Force the ball wide into traps.', 'Stay compact centrally.', 'Rotate the press.'],
            'winning' => ['Reduce pressing intensity.', 'Lower the line.', 'Slow the tempo with possession.'],
            'losing' => ['Press constantly and push the line high.', 'Add box runners.', 'Increase tempo and crossing volume.'],
        ],
        'adjustments' => [
            ['situation' => 'Opponent is pressing high', 'options' => ['Use the keeper and split centre-backs', 'Go long to the striker', 'Trigger the inside forwards in behind', 'Keep the pivot as an outlet']],
            ['situation' => 'Opponent is defending very deep', 'options' => ['Push both full-backs high', 'Add late runners into the box', 'Use crosses and cut-backs', 'Increase width']],
            ['situation' => 'You are protecting a lead', 'options' => ['Reduce pressing intensity', 'Lower the line', 'Keep the full-backs home', 'Keep possession to protect the lead']],
        ],
    ],

    [
        'id' => 'sjafri-indonesia-u23-2023',
        'manager' => 'Indra Sjafri',
        'club' => 'Indonesia U-23',
        'season' => '2023',
        'formation' => '4-2-3-1',
        'style' => ['Balanced', 'Counter Attack', 'Compact'],
        'difficulty' => 'Intermediate',
        'description' => "Inspired by Sjafri's Indonesia U-23 at the 2023 SEA Games — an organised, resilient side that reached the final.",
        'philosophy' => "Inspired by Sjafri's Indonesia U-23: stay balanced and compact, work hard as a unit, and attack efficiently on the counter.",
        'withBall' => '4-2-3-1',
        'withoutBall' => '4-4-2',
        'gameModes' => ['Career Mode', 'Clubs', 'Kick-Off'],
        'tags' => ['Balanced', 'Counter Attack', 'Compact', 'Direct'],
        'dna' => ['Possession' => 60, 'Pressing' => 72, 'Directness' => 72, 'Defensive Solidity' => 84, 'Width' => 68, 'Tempo' => 76, 'Counter-Attacking' => 82, 'Creativity' => 68],
        'variations' => ['4-3-3', '4-4-2'],
        'buildUp' => 'Balanced',
        'defensiveApproach' => 'Mid Block',
        'width' => 5,
        'depth' => 6,
        'attackingFocus' => 'Counter Attack',
        'phases' => [
            'buildUp' => 'Controlled and safe. The centre-backs split, the double pivot screens, and the full-backs support. The ball is moved forward without risk.',
            'progression' => 'Direct and wide. The number ten finds space while the wide players attack the flanks. The ball is moved forward quickly once the opponent commits.',
            'finalThird' => 'The striker pins the centre-backs, the number ten creates, and the wide players attack the box. Chances come from quick counters and crosses.',
            'defensiveTransition' => 'Press the ball immediately, then recover into the compact 4-4-2 and counter.',
            'defensiveShape' => 'A compact 4-4-2 with the number ten dropping into midfield. The block protects the centre and forces the opponent wide.',
        ],
        'howToPlay' => [
            'haveBall' => ['Stay balanced and hard-working.', 'Use the wide players.', 'Feed the number ten between the lines.', 'Attack quickly on the transition.'],
            'loseBall' => ['Press the ball immediately.', 'Drop into the 4-4-2.', 'Protect the central lane.', 'Stay disciplined.'],
            'opponentBall' => ['Keep two compact banks.', 'Force the opponent wide.', 'Stay patient and organised.', 'Protect the box.'],
            'winning' => ['Drop the block deeper.', 'Reduce attacking commitment.', 'Keep the number ten as a counter outlet.'],
            'losing' => ['Push the full-backs higher.', 'Add a runner from midfield.', 'Increase tempo and crossing volume.'],
        ],
        'adjustments' => [
            ['situation' => 'Opponent is pressing high', 'options' => ['Go long to the striker', 'Use the wide players as outlets', 'Keep the double pivot as a safe option', 'Avoid risk in your own half']],
            ['situation' => 'Opponent is defending very deep', 'options' => ['Push the full-backs high', 'Add a late central runner', 'Increase crosses and cut-backs', 'Use set pieces']],
            ['situation' => 'You are protecting a lead', 'options' => ['Keep two compact banks', 'Reduce attacking commitment', 'Use the number ten as a counter outlet', 'Slow the tempo']],
        ],
    ],

    [
        'id' => 'sjafri-bali-united-2014',
        'manager' => 'Indra Sjafri',
        'club' => 'Bali United',
        'season' => '2014',
        'formation' => '4-3-3',
        'style' => ['Attacking', 'High Press', 'Wide Play'],
        'difficulty' => 'Intermediate',
        'description' => "Inspired by Sjafri's Bali United — an attack-minded, energetic club side built on pressing and wide play.",
        'philosophy' => "Inspired by Sjafri's Bali United: press with intensity, attack with width, and play an energetic, front-foot brand of football.",
        'withBall' => '4-3-3',
        'withoutBall' => '4-4-2',
        'gameModes' => ['Career Mode', 'Clubs', 'Kick-Off'],
        'tags' => ['Attacking', 'High Press', 'Wide', 'Fast Wingers'],
        'dna' => ['Possession' => 72, 'Pressing' => 80, 'Directness' => 68, 'Defensive Solidity' => 70, 'Width' => 82, 'Tempo' => 84, 'Counter-Attacking' => 74, 'Creativity' => 78],
        'variations' => ['4-2-3-1', '4-4-2'],
        'buildUp' => 'Fast Build Up',
        'defensiveApproach' => 'High Press',
        'width' => 7,
        'depth' => 7,
        'attackingFocus' => 'Wide Play',
        'phases' => [
            'buildUp' => 'Quick and positive. The centre-backs split, the pivot screens, and the full-backs push high. The goalkeeper distributes fast to start attacks.',
            'progression' => 'Wide and attacking. The wingers beat their man while the midfielders support. The ball is moved to the flanks quickly and crosses are delivered early.',
            'finalThird' => 'The striker attacks the box, the wingers deliver, and the midfielders arrive late. Chances come from wide play and quick combinations.',
            'defensiveTransition' => 'Aggressive counter-press to win the ball back high and attack an unset defence.',
            'defensiveShape' => 'A high 4-4-2 pressing block with the wide forwards dropping into midfield. The block compresses the pitch and forces the opponent wide.',
        ],
        'howToPlay' => [
            'haveBall' => ['Attack with width and pace.', 'Feed the wingers quickly.', 'Push the full-backs high.', 'Cross early and often.'],
            'loseBall' => ['Counter-press immediately.', 'Win the ball back high.', 'Recover into the 4-4-2 if needed.', 'Press in coordinated bursts.'],
            'opponentBall' => ['Keep a high line.', 'Force the ball wide into traps.', 'Stay compact centrally.', 'Rotate the press.'],
            'winning' => ['Reduce pressing intensity.', 'Lower the line.', 'Slow the tempo with possession.'],
            'losing' => ['Press constantly and push the line high.', 'Add box runners.', 'Increase tempo and crossing volume.'],
        ],
        'adjustments' => [
            ['situation' => 'Opponent is pressing high', 'options' => ['Use the keeper and split centre-backs', 'Go long to the striker', 'Release the wingers in behind', 'Keep the pivot as an outlet']],
            ['situation' => 'Opponent is defending very deep', 'options' => ['Push both full-backs high', 'Add late runners into the box', 'Use crosses and cut-backs', 'Increase width to the touchline']],
            ['situation' => 'You are protecting a lead', 'options' => ['Reduce pressing intensity', 'Lower the line', 'Keep the full-backs home', 'Keep possession to protect the lead']],
        ],
    ],

    [
        'id' => 'sjafri-indonesia-u20-2024',
        'manager' => 'Indra Sjafri',
        'club' => 'Indonesia U-20',
        'season' => '2024',
        'formation' => '3-4-2-1',
        'style' => ['High Press', 'Compact', 'Counter Attack'],
        'difficulty' => 'Advanced',
        'description' => "Inspired by Sjafri's Indonesia U-20 in the 2024 era — a modern back three with disciplined wing-backs and quick counters.",
        'philosophy' => "Inspired by Sjafri's Indonesia U-20: defend in a disciplined back three, work hard in coordinated blocks, and counter sharply through fast wide players.",
        'withBall' => '3-2-5',
        'withoutBall' => '5-4-1',
        'gameModes' => ['Career Mode', 'Clubs', 'Kick-Off'],
        'tags' => ['High Press', 'Compact', 'Counter Attack', 'Attacking Fullbacks'],
        'dna' => ['Possession' => 58, 'Pressing' => 84, 'Directness' => 76, 'Defensive Solidity' => 86, 'Width' => 74, 'Tempo' => 86, 'Counter-Attacking' => 88, 'Creativity' => 70],
        'variations' => ['3-4-3', '5-3-2'],
        'buildUp' => 'Fast Build Up',
        'defensiveApproach' => 'Mid Block',
        'width' => 6,
        'depth' => 7,
        'attackingFocus' => 'Counter Attack',
        'phases' => [
            'buildUp' => 'Structured and safe. The back three splits with the ball-playing defenders stepping out. The wing-backs start deep and the ball is moved forward quickly.',
            'progression' => 'The two central midfielders link play while the wing-backs provide width. The team looks to progress the ball quickly into the final third.',
            'finalThird' => 'The striker pins the centre-backs, the two inside forwards attack the half-spaces, and the wing-backs deliver crosses. Chances come from fast breaks.',
            'defensiveTransition' => 'Coordinated counter-press in wide areas, then recovery into the back five and a fast counter.',
            'defensiveShape' => 'A compact 5-4-1 with the wing-backs dropping into the back five and the inside forwards tucking into midfield. The block is disciplined and protects the centre.',
        ],
        'howToPlay' => [
            'haveBall' => ['Build from the back three safely.', 'Use the wing-backs for width.', 'Break quickly through the inside forwards.', 'Attack fast on the transition.'],
            'loseBall' => ['Counter-press, then drop into the 5-4-1.', 'Keep the wing-backs disciplined.', 'Protect the central lane.', 'Launch fast counters.'],
            'opponentBall' => ['Keep the back five compact.', 'Screen the centre with the midfield four.', 'Force the opponent wide.', 'Stay patient and organised.'],
            'winning' => ['Drop the wing-backs into a deeper five.', 'Reduce attacking commitment.', 'Keep possession in safe areas.'],
            'losing' => ['Push the wing-backs high.', 'Move an inside forward closer to the striker.', 'Increase tempo and crossing volume.'],
        ],
        'adjustments' => [
            ['situation' => 'Opponent is pressing high', 'options' => ['Spread the back three wide', 'Use the ball-playing defenders to step out', 'Use the wing-backs as outlets', 'Go long to the striker']],
            ['situation' => 'Opponent is defending very deep', 'options' => ['Push both wing-backs high', 'Overload the box with the inside forwards', 'Use crosses and cut-backs', 'Increase width']],
            ['situation' => 'You are protecting a lead', 'options' => ['Drop the wing-backs into a five', 'Keep the block compact', 'Reduce attacking risk', 'Use the striker to hold the ball']],
        ],
    ],
];
